name: R-CMD-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        r-version: ['release']   # Use latest stable R

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up R
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # 3. Install system dependencies (gfortran & libpng)
      - name: Install system dependencies
        run: |
          brew install gcc          # includes gfortran
          brew install libpng

      # 4. Cache R package dependencies
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.r-version }}-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.r-version }}-

      # 5. Install R dependencies (prefer binaries)
      - name: Install dependencies
        run: |
          install.packages("remotes", repos="https://cloud.r-project.org")
          install.packages("Matrix", repos="https://cloud.r-project.org", type="binary")
          remotes::install_deps("ETRep", dependencies = TRUE, type="binary")
        shell: Rscript {0}

      # 6. Run R CMD check
      - name: Check
        run: |
          install.packages("rcmdcheck", repos="https://cloud.r-project.org")
          rcmdcheck::rcmdcheck("ETRep", args = "--no-manual", error_on = "error")
        shell: Rscript {0}
