name: R-CMD-check-Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        r-version: ['release']   # Latest stable R

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Set up R on Windows
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # 3. Cache installed R packages
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.r-version }}-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.r-version }}-

      # 4. Install R dependencies (prefer Windows binaries)
      - name: Install dependencies
        run: |
          install.packages("remotes", repos="https://cloud.r-project.org", type="binary")
          install.packages("Matrix", repos="https://cloud.r-project.org", type="binary")
          remotes::install_deps("ETRep", dependencies = TRUE, type="binary")
        shell: Rscript {0}

      # 5. Run R CMD check
      - name: Run R CMD check
        run: |
          install.packages("rcmdcheck", repos="https://cloud.r-project.org", type="binary")
          rcmdcheck::rcmdcheck("ETRep", args = "--no-manual", error_on = "error")
        shell: Rscript {0}
